---
abstract: 'Multi-Apps Runner'
author:
  - 'Michael Vu <email@michael.vu>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Munner
no_index:
  package:
    - App::Munner::Runner
requires:
  Cwd: '0'
  Daemon::Control: '0'
  File::Temp: '0'
  Getopt::Long::Descriptive: '0'
  IPC::Signal: '0'
  List::MoreUtils: '0'
  Mo: '0'
  Module::Load: '0'
  Parallel::ForkManager: '0'
  Unix::PID: '0'
  YAML: '0'
version: '0.52'
