---
abstract: 'Multi-Apps Runner'
author:
  - 'Michael Vu <email@michael.vu>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Munner
requires:
  Getopt::Long::Descriptive: '0'
  Parallel::ForkManager: '0'
  YAML: '0'
version: '0.2'
